spring:
 profiles:
  active: hsql
---  
spring:
 profiles: mysql
 jpa:
  database: MYSQL
  show-sql: true
  hibernate:
   ddl-auto: create
 datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/test
  username: root  
---  
#management application properties
server:
    port: 8080    
#invoke with: http://localhost:8081/mappings
management:
    port: 8081
    address: 127.0.0.1
http:
    mappers: 
       jsonPrettyPrint: true

